apiVersion: apps/v1
kind: Deployment
metadata:
  name: connectorsapi-deployment
  labels:
    app: connectorsapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: connectorsapi
  template:
    metadata:
      labels:
        app: connectorsapi
    spec:
      containers:
      - name: connectorsapi
        image: yevhen0825/connectorsapi:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        env:
          - name: ASPNETCORE_ENVIRONMENT
            value: Development
          - name: ASPNETCORE_HTTP_PORTS
            value: "8080"
          - name: ConnectionStrings__DefaultConnection
            valueFrom:
              secretKeyRef:
                name: mssql-db-secret
                key: mssql-main-db-connection-string
          - name: ConnectionStrings__Redis
            value: "redis-0.redis.csms.svc.cluster.local:6379,password=redis-complex-password"
          - name: MessageBrokerSettings__RabbitMqHost
            value: "rabbitmq-0.rabbitmq.csms.svc.cluster.local"
          - name: MessageBrokerSettings__RabbitMqUsername
            valueFrom:
              secretKeyRef:
                name: rabbitmq-secret
                key: rabbitmq-username
          - name: MessageBrokerSettings__RabbitMqPassword
            valueFrom:
              secretKeyRef:
                name: rabbitmq-secret
                key: rabbitmq-password
        resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: connectorsapi-service
  labels:
    app: connectorsapi
spec:
  type: LoadBalancer
  selector:
    app: connectorsapi
  ports:
    - protocol: TCP
      name: http
      port: 8004
      targetPort: 8080