# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

parameters:
- name: 'projectsToBuild'
  type: object
  default:
    - path: "$(Build.SourcesDirectory)/ChargingStation.Backend/Services/Depots/ChargingStation.Depots"
      imageName: "depotsapi"

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '71b76521-feff-48e9-aef4-f0dd85171cdf'
  imageRepository: 'depotsapi'
  containerRegistry: 'yechuacr2508.azurecr.io'
  dockerBuildContext: '$(Build.SourcesDirectory)/ChargingStation.Backend'
  dockerfilePath: '$(Build.SourcesDirectory)/ChargingStation.Backend/Services/Depots/ChargingStation.Depots/Dockerfile'
  tag: '$(Build.BuildId)'
  # Agent VM image name
  vmImageName: 'ubuntu-latest'    

stages:
- stage: Build
  displayName: Build and push stage
  jobs:
  - ${{ each project in parameters.projectsToBuild }}:
    - job: 'Build_${{ project.imageName }}'
      displayName: Build and push image into ACR
      pool:
        vmImage: $(vmImageName)
      steps:
      - task: Docker@2
        displayName: Build and push an image to container registry
        inputs:
          command: buildAndPush
          repository: $(imageRepository)
          dockerfile: ${{ project.path }}/Dockerfile
          containerRegistry: $(dockerRegistryServiceConnection)
          buildContext: $(dockerBuildContext)
          tags: |
            $(tag)
