apiVersion: v1
kind: Secret
metadata:
  name: azure-storage-secret
type: Opaque
data:
  azure-storage-connection-string: RGVmYXVsdEVuZHBvaW50c1Byb3RvY29sPWh0dHBzO0FjY291bnROYW1lPWNzbXMyNTA4MTtBY2NvdW50S2V5PUVxNXh2TG5DSWhRL0ZGSysvT0ZTaDZEYmltMUtaUnJiNUlKRjVKa1VPMll5enhpSWNPUngvcFpQTStvWXpSbDkyd1R1QXhKeVV5REQrQVN0SjVKZCtRPT07RW5kcG9pbnRTdWZmaXg9Y29yZS53aW5kb3dzLm5ldA==
