apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  mongo-root-username: "cm9vdA=="
  mongo-root-password: "cm9vdA=="
  # mongo-db-connection-string: "mongodb://root:root@mongo-0.mongo.csms.svc.cluster.local:27017