apiVersion: v1
kind: Secret
metadata:
  name: mssql-db-secret
type: Opaque
data:
  # echo -n "cookie-value" | base64
  mssql-main-db-connection-string: U2VydmVyPXRjcDpjc21zLmRhdGFiYXNlLndpbmRvd3MubmV0LDE0MzM7SW5pdGlhbCBDYXRhbG9nPWNzbXMtZGI7UGVyc2lzdCBTZWN1cml0eSBJbmZvPUZhbHNlO1VzZXIgSUQ9c3FsYWRtaW47UGFzc3dvcmQ9d2ZkNzc1WDc4OTAxMjM0NTY7TXVsdGlwbGVBY3RpdmVSZXN1bHRTZXRzPUZhbHNlO0VuY3J5cHQ9VHJ1ZTtUcnVzdFNlcnZlckNlcnRpZmljYXRlPUZhbHNlO0Nvbm5lY3Rpb24gVGltZW91dD0zMDs=
  mssql-hangfire-db-connection-string: U2VydmVyPXRjcDpjc21zLmRhdGFiYXNlLndpbmRvd3MubmV0LDE0MzM7SW5pdGlhbCBDYXRhbG9nPWNzbXMtaGFuZ2ZpcmU7UGVyc2lzdCBTZWN1cml0eSBJbmZvPUZhbHNlO1VzZXIgSUQ9c3FsYWRtaW47UGFzc3dvcmQ9d2ZkNzc1WDc4OTAxMjM0NTY7TXVsdGlwbGVBY3RpdmVSZXN1bHRTZXRzPUZhbHNlO0VuY3J5cHQ9VHJ1ZTtUcnVzdFNlcnZlckNlcnRpZmljYXRlPUZhbHNlO0Nvbm5lY3Rpb24gVGltZW91dD0zMDs=