apiVersion: apps/v1
kind: Deployment
metadata:
  name: heartbeatsapi-deployment
  labels:
    app: heartbeatsapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: heartbeatsapi
  template:
    metadata:
      labels:
        app: heartbeatsapi
    spec:
      containers:
      - name: heartbeatsapi
        image: csmsacr2508.azurecr.io/heartbeatsapi:104
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        env:
          - name: ASPNETCORE_ENVIRONMENT
            value: Development
          - name: ASPNETCORE_HTTP_PORTS
            value: "8080"
          - name: ConnectionStrings__DefaultConnection
            valueFrom:
              secretKeyRef:
                name: mssql-db-secret
                key: mssql-main-db-connection-string
          - name: ConnectionStrings__AzureTableStorage
            valueFrom:
              secretKeyRef:
                name: azure-storage-secret
                key: azure-storage-connection-string
          - name: MessageBrokerSettings__RabbitMqHost
            value: "rabbitmq-0.rabbitmq.csms.svc.cluster.local"
          - name: MessageBrokerSettings__RabbitMqUsername
            valueFrom:
              secretKeyRef:
                name: rabbitmq-secret
                key: rabbitmq-username
          - name: MessageBrokerSettings__RabbitMqPassword
            valueFrom:
              secretKeyRef:
                name: rabbitmq-secret
                key: rabbitmq-password
          - name: GrpcSettings__ChargePointServiceAddress
            valueFrom:
              configMapKeyRef:
                name: chargepoints-config
                key: chargepoints-grpc-url
        resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: heartbeatsapi-service
  labels:
    app: heartbeatsapi
spec:
  selector:
    app: heartbeatsapi
  ports:
    - protocol: TCP
      name: http
      port: 8080
      targetPort: 8080