version: '3.4'

services:
  chargingstation_rabbitmq:
    image: rabbitmq:3-management-alpine
    
  chargingstation_redis:
    image: redis:alpine

  chargingstation.aggregator:
    image: ${DOCKER_REGISTRY-}aggregator
    build:
      context: .
      dockerfile: API/ChargingStation.Aggregator/Dockerfile

  chargingstation.gateway:
    image: ${DOCKER_REGISTRY-}gateway
    build:
      context: .
      dockerfile: ChargingStation.Gateway/Dockerfile
  
  depots.api:
    image: ${DOCKER_REGISTRY-}depotsapi
    build:
      context: .
      dockerfile: API/ChargingStation.Depots/Dockerfile
      
  chargepoints.api:
    image: ${DOCKER_REGISTRY-}chargepointsapi
    build:
      context: .
      dockerfile: API/ChargingStation.ChargePoints/Dockerfile
      
  chargepoints.grpc:
    image: ${DOCKER_REGISTRY-}chargepointsgrpc
    build:
      context: .
      dockerfile: GRPC/ChargingStation.ChargePoints.Grpc/Dockerfile
      
  ocpptags.api:
    image: ${DOCKER_REGISTRY-}ocpptagsapi
    build:
      context: .
      dockerfile: API/ChargingStation.OcppTags/Dockerfile
      
  ocpptags.grpc:
    image: ${DOCKER_REGISTRY-}ocpptagsgrpc
    build:
      context: .
      dockerfile: GRPC/ChargingStation.OcppTags.Grpc/Dockerfile
      
  connectors.api:
    image: ${DOCKER_REGISTRY-}connectorsapi
    build:
      context: .
      dockerfile: API/ChargingStation.Connectors/Dockerfile
      
  connectors.grpc:
    image: ${DOCKER_REGISTRY-}connectorsgrpc
    build:
      context: .
      dockerfile: GRPC/ChargingStation.Connectors.Grpc/Dockerfile
      
  transactions.api:
    image: ${DOCKER_REGISTRY-}transactionsapi
    build:
      context: .
      dockerfile: API/ChargingStation.Transactions/Dockerfile
      
  heartbeats.api:
    image: ${DOCKER_REGISTRY-}heartbeatsapi
    build:
      context: .
      dockerfile: API/ChargingStation.Heartbeats/Dockerfile
      
  reservations.api:
    image: ${DOCKER_REGISTRY-}reservationsapi
    build:
      context: .
      dockerfile: API/ChargingStation.Reservations/Dockerfile
      
  chargingprofiles.api:
    image: ${DOCKER_REGISTRY-}chargingprofilesapi
    build:
      context: .
      dockerfile: API/ChargingStation.ChargingProfiles/Dockerfile
      
  chargingstation.websockets:
    image: ${DOCKER_REGISTRY-}chargingstationwebsockets
    build:
      context: .
      dockerfile: API/ChargingStation.WebSockets/Dockerfile

  chargingstation.signalr:
    image: ${DOCKER_REGISTRY-}signalr
    build:
      context: .
      dockerfile: API/ChargingStation.SignalR/Dockerfile