version: '3.4'

services:
  chargingstation_rabbitmq:
    image: rabbitmq:3.13.2-management-alpine
    
  chargingstation_redis:
    image: redis:7.2.5-alpine

  chargingstation.aggregator:
    image: ${DOCKER_REGISTRY-}aggregator
    build:
      context: .
      dockerfile: Services/Aggregator/Aggregator/Dockerfile

  chargingstation.gateway:
    image: ${DOCKER_REGISTRY-}gateway
    build:
      context: .
      dockerfile: Services/Gateway/ChargingStation.Gateway/Dockerfile
  
  depots.api:
    image: ${DOCKER_REGISTRY-}depotsapi
    build:
      context: .
      dockerfile: Services/Depots/ChargingStation.Depots/Dockerfile
      
  chargepoints.api:
    image: ${DOCKER_REGISTRY-}chargepointsapi
    build:
      context: .
      dockerfile: Services/ChargePoints/ChargePoints.Api/Dockerfile
      
  chargepoints.grpc:
    image: ${DOCKER_REGISTRY-}chargepointsgrpc
    build:
      context: .
      dockerfile: Services/ChargePoints/ChargePoints.Grpc/Dockerfile
      
  ocpptags.api:
    image: ${DOCKER_REGISTRY-}ocpptagsapi
    build:
      context: .
      dockerfile: Services/OcppTags/OcppTags.Api/Dockerfile
      
  ocpptags.grpc:
    image: ${DOCKER_REGISTRY-}ocpptagsgrpc
    build:
      context: .
      dockerfile: Services/OcppTags/OcppTags.Grpc/Dockerfile
      
  connectors.api:
    image: ${DOCKER_REGISTRY-}connectorsapi
    build:
      context: .
      dockerfile: Services/Connectors/Connectors.Api/Dockerfile
      
  connectors.grpc:
    image: ${DOCKER_REGISTRY-}connectorsgrpc
    build:
      context: .
      dockerfile: Services/Connectors/Connectors.Grpc/Dockerfile
      
  transactions.api:
    image: ${DOCKER_REGISTRY-}transactionsapi
    build:
      context: .
      dockerfile: Services/Transactions/Transactions.Api/Dockerfile
      
  transactions.grpc:
    image: ${DOCKER_REGISTRY-}transactionsgrpc
    build:
      context: .
      dockerfile: Services/Transactions/Transactions.Grpc/Dockerfile
      
  heartbeats.api:
    image: ${DOCKER_REGISTRY-}heartbeatsapi
    build:
      context: .
      dockerfile: Services/Heartbeats/ChargingStation.Heartbeats/Dockerfile
      
  reservations.api:
    image: ${DOCKER_REGISTRY-}reservationsapi
    build:
      context: .
      dockerfile: Services/Reservations/Reservations.Api/Dockerfile
      
  reservations.grpc:
    image: ${DOCKER_REGISTRY-}reservationsgrpc
    build:
      context: .
      dockerfile: Services/Reservations/Reservations.Grpc/Dockerfile
      
  chargingprofiles.api:
    image: ${DOCKER_REGISTRY-}chargingprofilesapi
    build:
      context: .
      dockerfile: Services/ChargingProfiles/ChargingStation.ChargingProfiles/Dockerfile
      
  energyconsumptionsettings.api:
    image: ${DOCKER_REGISTRY-}energyconsumptionsettingsapi
    build:
      context: .
      dockerfile: Services/EnergyConsumption/EnergyConsumption.Api/Dockerfile
      
  energyconsumptionsettings.grpc:
    image: ${DOCKER_REGISTRY-}energyconsumptionsettingsgrpc
    build:
      context: .
      dockerfile: Services/EnergyConsumption/EnergyConsumption.Grpc/Dockerfile
      
  chargingstation.websockets:
    image: ${DOCKER_REGISTRY-}chargingstationwebsockets
    build:
      context: .
      dockerfile: Services/WebSockets/ChargingStation.WebSockets/Dockerfile

  chargingstation.signalr:
    image: ${DOCKER_REGISTRY-}signalr
    build:
      context: .
      dockerfile: Services/SignalR/ChargingStation.SignalR/Dockerfile

  usermanagement.api:
    image: ${DOCKER_REGISTRY-}usermanagement
    build:
      context: .
      dockerfile: Services/UserManagement/UserManagement.API/Dockerfile
  
  emulator_db:
    image: mongo:4.4
  
  chargingstation_emulator:
    image: ${DOCKER_REGISTRY-}emulator
    build:
      context: .
      dockerfile: Emulator/ChargePointEmulator.UI/Dockerfile
      
volumes:
  mongo_data: