version: '3.4'

services:
  chargingstation_rabbitmq:
    container_name: chargingstation_rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
        
  chargingstation_redis:
    container_name: chargingstation_redis
    restart: always
    ports:
      - "6379:6379"
  
  chargingstation.aggregator:
    container_name: chargingstation.aggregator
    restart: always
    ports:
      - "8025:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - "ApiSettings:DepotServiceAddress=http://depots.api:8080"
      - "ApiSettings:ChargePointsServiceAddress=http://chargepoints.api:8080"
      - "ApiSettings:ConnectorsServiceAddress=http://connectors.api:8080"
      - "ApiSettings:EnergyConsumptionSettingsServiceAddress=http://energyconsumptionsettings.api:8080/api/EnergyConsumptionSettings/"
      - "ApiSettings:WebsocketsServiceAddress=http://chargingstation.websockets:8080"
    depends_on:
      - depots.api
      - chargepoints.api
      - connectors.api
      - energyconsumptionsettings.api
      - chargingstation.websockets
  
  chargingstation.gateway:
    container_name: chargingstation.gateway
    restart: always
    ports:
      - "8000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
        
  depots.api:
    container_name: depots.api
    ports:
      - "8001:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - "ConnectionStrings:DefaultConnection=Server=tcp:sql-csms-yechu.database.windows.net,1433;Initial Catalog=db-csms-yechu;Persist Security Info=False;User ID=sqladmin;Password=wfd775X7890123456;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;"
        
  chargepoints.api:
    container_name: chargepoints.api
    ports:
      - "8002:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - "ConnectionStrings:DefaultConnection=Server=tcp:sql-csms-yechu.database.windows.net,1433;Initial Catalog=db-csms-yechu;Persist Security Info=False;User ID=sqladmin;Password=wfd775X7890123456;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;"
      - "MessageBrokerSettings:HostAddress=amqp://guest:guest@chargingstation_rabbitmq:5672"
    depends_on:
      - chargingstation_rabbitmq
      - depots.api
      
  chargepoints.grpc:
    container_name: chargepoints.grpc
    ports:
      - "8052:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - "ConnectionStrings:DefaultConnection=Server=tcp:sql-csms-yechu.database.windows.net,1433;Initial Catalog=db-csms-yechu;Persist Security Info=False;User ID=sqladmin;Password=wfd775X7890123456;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;"
      - "MessageBrokerSettings:HostAddress=amqp://guest:guest@chargingstation_rabbitmq:5672"
    depends_on:
      - chargingstation_rabbitmq
      - depots.api
  
  ocpptags.api:
    container_name: ocpptags.api
    ports:
      - "8003:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - "ConnectionStrings:DefaultConnection=Server=tcp:sql-csms-yechu.database.windows.net,1433;Initial Catalog=db-csms-yechu;Persist Security Info=False;User ID=sqladmin;Password=wfd775X7890123456;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;"
      - "MessageBrokerSettings:HostAddress=amqp://guest:guest@chargingstation_rabbitmq:5672"
    depends_on:
      - chargingstation_rabbitmq
      - depots.api
  
  ocpptags.grpc:
    container_name: ocpptags.grpc
    ports:
      - "8053:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - "ConnectionStrings:DefaultConnection=Server=tcp:sql-csms-yechu.database.windows.net,1433;Initial Catalog=db-csms-yechu;Persist Security Info=False;User ID=sqladmin;Password=wfd775X7890123456;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;"
      - "MessageBrokerSettings:HostAddress=amqp://guest:guest@chargingstation_rabbitmq:5672"
    depends_on:
        - chargingstation_rabbitmq
        - depots.api
  
  connectors.api:
    container_name: connectors.api
    ports:
      - "8004:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - "ConnectionStrings:DefaultConnection=Server=tcp:sql-csms-yechu.database.windows.net,1433;Initial Catalog=db-csms-yechu;Persist Security Info=False;User ID=sqladmin;Password=wfd775X7890123456;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;"
      - "MessageBrokerSettings:HostAddress=amqp://guest:guest@chargingstation_rabbitmq:5672"
    depends_on:
      - chargingstation_rabbitmq
      - depots.api
  
  connectors.grpc:
    container_name: connectors.grpc
    ports:
      - "8054:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - "ConnectionStrings:DefaultConnection=Server=tcp:sql-csms-yechu.database.windows.net,1433;Initial Catalog=db-csms-yechu;Persist Security Info=False;User ID=sqladmin;Password=wfd775X7890123456;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;"
      - "MessageBrokerSettings:HostAddress=amqp://guest:guest@chargingstation_rabbitmq:5672"
    depends_on:
      - chargingstation_rabbitmq
      - depots.api
  
  transactions.api:
    container_name: transactions.api
    ports:
      - "8005:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - "ConnectionStrings:DefaultConnection=Server=tcp:sql-csms-yechu.database.windows.net,1433;Initial Catalog=db-csms-yechu;Persist Security Info=False;User ID=sqladmin;Password=wfd775X7890123456;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;"
      - "MessageBrokerSettings:HostAddress=amqp://guest:guest@chargingstation_rabbitmq:5672"
      - "ApiSettings:EnergyConsumptionSettingsServiceAddress=http://chargingprofiles.api:8080/api/EnergyConsumptionSettings/"
      - "GrpcSettings:ChargePointServiceAddress=http://chargepoints.grpc:8080"
      - "GrpcSettings:OcppTagServiceAddress=http://ocpptags.grpc:8080"
      - "GrpcSettings:ConnectorServiceAddress=http://connectors.grpc:8080"
      - "GrpcSettings:ReservationServiceAddress=http://reservations.grpc:8080"
    depends_on:
      - chargingstation_rabbitmq
      - depots.api
  
  transactions.grpc:
    container_name: transactions.grpc
    ports:
      - "8055:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - "ConnectionStrings:DefaultConnection=Server=tcp:sql-csms-yechu.database.windows.net,1433;Initial Catalog=db-csms-yechu;Persist Security Info=False;User ID=sqladmin;Password=wfd775X7890123456;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;"
      - "MessageBrokerSettings:HostAddress=amqp://guest:guest@chargingstation_rabbitmq:5672"
      - "GrpcSettings:EnergyConsumptionSettingsServiceAddress=http://energyconsumptionsettings.grpc:8080"
      - "GrpcSettings:ChargePointServiceAddress=http://chargepoints.grpc:8080"
      - "GrpcSettings:OcppTagServiceAddress=http://ocpptags.grpc:8080"
      - "GrpcSettings:ConnectorServiceAddress=http://connectors.grpc:8080"
      - "GrpcSettings:ReservationServiceAddress=http://reservations.grpc:8080"
    depends_on:
      - chargingstation_rabbitmq
      - depots.api
  
  heartbeats.api:
    container_name: heartbeats.api
    ports:
      - "8006:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - "ConnectionStrings:DefaultConnection=Server=tcp:sql-csms-yechu.database.windows.net,1433;Initial Catalog=db-csms-yechu;Persist Security Info=False;User ID=sqladmin;Password=wfd775X7890123456;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;"
      - "MessageBrokerSettings:HostAddress=amqp://guest:guest@chargingstation_rabbitmq:5672"
      - "GrpcSettings:ChargePointServiceAddress=http://chargepoints.grpc:8080"
    depends_on:
      - chargingstation_rabbitmq
      - depots.api
        
  reservations.api:
    container_name: reservations.api
    ports:
      - "8007:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - "ConnectionStrings:DefaultConnection=Server=tcp:sql-csms-yechu.database.windows.net,1433;Initial Catalog=db-csms-yechu;Persist Security Info=False;User ID=sqladmin;Password=wfd775X7890123456;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;"
      - "ConnectionStrings:HangfireConnection=Server=tcp:sql-csms-yechu.database.windows.net,1433;Initial Catalog=db-hangfire-yechu;Persist Security Info=False;User ID=sqladmin;Password=wfd775X7890123456;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;"
      - "MessageBrokerSettings:HostAddress=amqp://guest:guest@chargingstation_rabbitmq:5672"
      - "GrpcSettings:ChargePointServiceAddress=http://chargepoints.grpc:8080"
      - "GrpcSettings:OcppTagServiceAddress=http://ocpptags.grpc:8080"
      - "GrpcSettings:ConnectorServiceAddress=http://connectors.grpc:8080"
    depends_on:
      - chargingstation_rabbitmq
  
  reservations.grpc:
    container_name: reservations.grpc
    ports:
      - "8057:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - "ConnectionStrings:DefaultConnection=Server=tcp:sql-csms-yechu.database.windows.net,1433;Initial Catalog=db-csms-yechu;Persist Security Info=False;User ID=sqladmin;Password=wfd775X7890123456;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;"
      - "ConnectionStrings:HangfireConnection=Server=tcp:sql-csms-yechu.database.windows.net,1433;Initial Catalog=db-hangfire-yechu;Persist Security Info=False;User ID=sqladmin;Password=wfd775X7890123456;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;"
      - "MessageBrokerSettings:HostAddress=amqp://guest:guest@chargingstation_rabbitmq:5672"
      - "GrpcSettings:ChargePointServiceAddress=http://chargepoints.grpc:8080"
      - "GrpcSettings:OcppTagServiceAddress=http://ocpptags.grpc:8080"
      - "GrpcSettings:ConnectorServiceAddress=http://connectors.grpc:8080"
  
  chargingprofiles.api:
    container_name: chargingprofiles.api
    ports:
      - "8008:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - "ConnectionStrings:DefaultConnection=Server=tcp:sql-csms-yechu.database.windows.net,1433;Initial Catalog=db-csms-yechu;Persist Security Info=False;User ID=sqladmin;Password=wfd775X7890123456;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;"
      - "MessageBrokerSettings:HostAddress=amqp://guest:guest@chargingstation_rabbitmq:5672"
      - "ApiSettings:ConnectorServiceAddress=http://connectors.api:8080"
      - "ApiSettings:TransactionServiceAddress=http://transactions.api:8080"
      - "ApiSettings:DepotServiceAddress=http://depots.api:8080"
      - "ApiSettings:ChargePointServiceAddress=http://chargepoints.api:8080"
      - "GrpcSettings:ConnectorServiceAddress=http://connectors.grpc:8080"
      - "GrpcSettings:ChargePointServiceAddress=http://chargepoints.grpc:8080"
    depends_on:
      - chargingstation_rabbitmq
      - depots.api
      - chargingstation_redis
  
  energyconsumptionsettings.api:
    container_name: energyconsumptionsettings.api
    ports:
      - "8009:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - "ConnectionStrings:DefaultConnection=Server=tcp:sql-csms-yechu.database.windows.net,1433;Initial Catalog=db-csms-yechu;Persist Security Info=False;User ID=sqladmin;Password=wfd775X7890123456;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;"
      - "ApiSettings:DepotServiceAddress=http://depots.api:8080"
      - "GrpcSettings:ChargePointServiceAddress=http://chargepoints.grpc:8080"
    depends_on:
      - chargingstation_rabbitmq
  
  energyconsumptionsettings.grpc:
    container_name: energyconsumptionsettings.grpc
    ports:
      - "8089:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - "ConnectionStrings:DefaultConnection=Server=tcp:sql-csms-yechu.database.windows.net,1433;Initial Catalog=db-csms-yechu;Persist Security Info=False;User ID=sqladmin;Password=wfd775X7890123456;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;"
      - "ApiSettings:DepotServiceAddress=http://depots.api:8080"
      - "GrpcSettings:ChargePointServiceAddress=http://chargepoints.grpc:8080"
    depends_on:
      - chargingstation_rabbitmq
  
  chargingstation.websockets:
    container_name: chargingstation.websockets
    ports:
      - "8020:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - "ApiSettings:ChargePointServiceAddress=http://chargepoints.api:8080"
      - "MessageBrokerSettings:HostAddress=amqp://guest:guest@chargingstation_rabbitmq:5672"
    depends_on:
      - chargingstation_rabbitmq
      - depots.api
   
  chargingstation.signalr:
    container_name: chargingstation.signalr
    ports:
      - "8030:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - "ApiSettings:ChargePointServiceAddress=http://chargepoints.api:8080"
      - "MessageBrokerSettings:HostAddress=amqp://guest:guest@chargingstation_rabbitmq:5672"
    depends_on:
      - chargingstation_rabbitmq