apiVersion: apps/v1
kind: Deployment
metadata:
  name: chargepointsapi-deployment
  labels:
    app: chargepointsapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chargepointsapi
  template:
    metadata:
      labels:
        app: chargepointsapi
    spec:
      containers:
      - name: chargepointsapi
        image: yevhen0825/chargepointsapi:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        env:
          - name: ASPNETCORE_ENVIRONMENT
            value: Development
          - name: ASPNETCORE_HTTP_PORTS
            value: "8080"
          - name: ConnectionStrings__DefaultConnection
            valueFrom:
              secretKeyRef:
                name: mssql-main-db-secret
                key: mssql-main-db-connection-string
          - name: MessageBrokerSettings__RabbitMqHost
            value: ""
          - name: MessageBrokerSettings__RabbitMqUsername
            valueFrom:
              secretKeyRef:
                name: rabbitmq-publisher
                key: rabbitmq-username
          - name: MessageBrokerSettings__RabbitMqPassword
            valueFrom:
              secretKeyRef:
                name: rabbitmq-publisher
                key: rabbitmq-password
        resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: chargepointsapi-service
  labels:
    app: chargepointsapi
spec:
  type: LoadBalancer
  selector:
    app: chargepointsapi
  ports:
    - protocol: TCP
      name: http
      port: 8002
      targetPort: 8080